name: lin_reg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pytorch=2.0
  - torch-geometric
  - torchvision
  - torchaudio
  - statsmodels
  - geopandas
  - contextily
  - networkx
  - plotly
  - jupyter
  - pip
  - pip:
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv