# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:16
    volumes:
      - ./install.sh:/docker-entrypoint-initdb.d/install.sh
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  jupyter:
    build: .
    volumes:
      - ./notebooks/:/home
    ports:
      - 8888:8888
    working_dir: /home


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
