name: housing-gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - geopandas
  - contextily
  - networkx
  - shapely
  - plotly
  - pip
  - pip:
      - torch
      - torch-geometric
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
