name: loan-gnn-transformer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - shap
  - networkx
  - pytorch
  - torchvision
  - pytorch-geometric
  - tensorflow
  - arviz
  - pip
  - pip:
      - torch-geometric
